module.exports = {
  'map': require('./my_lodash/map'),
  'each': require('./my_lodash/each'),
  'exist': require('./my_lodash/exist'),
  'filter_in': require('./my_lodash/filter_in'),
  'filter_out': require('./my_lodash/filter_out'),
  'first': require('./my_lodash/first'),
  'last': require('./my_lodash/last'),
  'max': require('./my_lodash/max'),
  'min': require('./my_lodash/min'),
  'sum': require('./my_lodash/sum'),
  'bubble_sort': require('./my_lodash/bubble_sort'),
  'range': require('./my_lodash/range'),
  'num_to_letter': require('./my_lodash/num_to_letter'),
};
